const test=require('node:test');const assert=require('node:assert/strict');const G=require('../dist/core.js');
test('all requested states and task identifiers are valid',()=>{assert.equal(G.tasks.length,19);assert.equal(new Set(G.tasks.map(t=>t.id)).size,19);assert.equal(G.statuses.length,7);for(const status of G.statuses)assert.equal(G.cleanState({scan:status}).scan,status);assert.equal(G.cleanState({scan:'corrupt'}).scan,'Not Started');});
test('before, during and after shift have bounded remaining time',()=>{const s=G.cleanState();assert.equal(G.summarize(600,s).remaining,510);assert.equal(G.summarize(810,s).remaining,510);assert.equal(G.summarize(1260,s).remaining,60);assert.equal(G.summarize(1330,s).remaining,0);assert.equal(G.position(600),0);assert.equal(G.position(1400),100);});
test('milestone boundaries include the current minute and advance afterward',()=>{const s=G.cleanState();assert.equal(G.summarize(1130,s).next.time,1130);assert.equal(G.summarize(1131,s).next.time,1140);assert.equal(G.summarize(1321,s).next,undefined);});
test('time does not complete tasks and exceptions remain open',()=>{const s=G.cleanState({scan:'Done',rotisserie:'Blocked',breaded:'Needs More Time'});const a=G.summarize(1321,s);assert.equal(a.done,1);assert.equal(a.open.length,18);assert.equal(a.blocked,1);assert.equal(a.extra,1);assert.equal(a.status,'Shift ended · work still open');});
test('finished shift requires all task states done',()=>{const s=Object.fromEntries(G.tasks.map(t=>[t.id,'Done']));assert.equal(G.summarize(1320,s).status,'Shift complete');assert.equal(G.summarize(1260,s).status,'Final closing hour');});
test('clock formats noon, midnight and durations',()=>{assert.equal(G.formatTime(0),'12:00 AM');assert.equal(G.formatTime(720),'12:00 PM');assert.equal(G.formatTime(1130),'6:50 PM');assert.equal(G.duration(-10),'0m');assert.equal(G.duration(255),'4h 15m');});

test('dependencies are validated and remain unfinished',()=>{assert.equal(G.cleanDependencies({scan:'Oven is in use'}).scan,'Oven is in use');assert.equal(G.cleanDependencies({scan:'invalid'}).scan,'');assert.equal(G.cleanDependencies().scan,'');const s=G.summarize(1320,G.cleanState({scan:'Dependency'}));assert.equal(s.dependencies,1);assert.equal(s.done,0);});

test('NA tasks are separate from done and do not leave work open',()=>{const state=Object.fromEntries(G.tasks.map(t=>[t.id,'NA Does not apply']));const s=G.summarize(1320,state);assert.equal(s.open.length,0);assert.equal(s.done,0);assert.equal(s.na,19);assert.equal(s.status,'Shift complete');});
test('old dinner completion does not complete the six new tasks',()=>{const s=G.cleanState({dinner:'Done',scan:'Started'});assert.equal(s.scan,'Started');const dinner=G.tasks.filter(t=>t.phase===1);assert.equal(dinner.length,6);for(const t of dinner)assert.equal(s[t.id],'Not Started');});
